/**
 * GALLERY IMAGES - Single Source of Truth
 *
 * Original sources: public/assets/images/photos/gallery/tattoo/
 * Optimized outputs: public/assets/images/photos/gallery/optimized/
 */

export interface GalleryImage {
  id: string;
  alt: string;
  src: string;
  optimizedSrc: string;
  title: string;
  category: string;
  style: string;
  width: number;
  height: number;
  objectPosition?: string;
  priority?: boolean;
}

type GalleryLocale = 'de' | 'en';

export type GalleryArtistId = 'debi' | 'loui' | 'luz';

export interface GalleryArtistOption {
  id: GalleryArtistId;
  label: string;
}

export interface GalleryFilterImage extends GalleryImage {
  artistId: GalleryArtistId;
  artistName: string;
  styleKey: string;
}

const GALLERY_ARTISTS: Record<GalleryArtistId, GalleryArtistOption> = {
  debi: { id: 'debi', label: 'Debi' },
  loui: { id: 'loui', label: 'Loui' },
  luz: { id: 'luz', label: 'Luz' },
};

const GALLERY_STYLE_LABELS: Record<string, Record<GalleryLocale, string>> = {
  Linienarbeit: { de: 'Linienarbeit', en: 'Linework' },
  Maori: { de: 'Maori', en: 'Maori' },
  'Old School': { de: 'Old School', en: 'Old School' },
  Realismus: { de: 'Realismus', en: 'Realism' },
  Biomechanisch: { de: 'Biomechanisch', en: 'Biomechanical' },
  Japanisch: { de: 'Japanisch', en: 'Japanese' },
  Portrait: { de: 'Portrait', en: 'Portrait' },
  Geometrisch: { de: 'Geometrisch', en: 'Geometric' },
  Blackwork: { de: 'Blackwork', en: 'Blackwork' },
  'Neo Traditional': { de: 'Neo Traditional', en: 'Neo Traditional' },
  Farbtattoo: { de: 'Farbtattoo', en: 'Color Tattoo' },
  Minimalistisch: { de: 'Minimalistisch', en: 'Minimalist' },
};

const DUPLICATE_GALLERY_IMAGE_IDS = new Set(['124']);

const getStyleKey = (style: string): string => {
  return style
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
};

const getLocalizedStyleLabel = (style: string, language: GalleryLocale): string => {
  return GALLERY_STYLE_LABELS[style]?.[language] ?? style;
};

const getLocalizedImageCopy = (
  image: GalleryFilterImage,
  language: GalleryLocale,
): Pick<GalleryImage, 'alt' | 'title' | 'category' | 'style'> => {
  if (language === 'de') {
    return {
      alt: image.alt,
      title: image.title,
      category: image.category,
      style: image.style,
    };
  }

  const localizedStyle = getLocalizedStyleLabel(image.style, language);
  const localizedCategory = getLocalizedStyleLabel(image.category, language);

  return {
    alt: `${localizedStyle} tattoo, piece ${image.id} from Medusa Studio`,
    title: `${localizedCategory} Piece ${image.id}`,
    category: localizedCategory,
    style: localizedStyle,
  };
};

const getArtistIdFromImage = (image: GalleryImage): GalleryArtistId | null => {
  const filename = image.src.split('/').pop()?.toLowerCase() ?? '';

  if (filename.startsWith('debi-')) return 'debi';
  if (filename.startsWith('loui-')) return 'loui';
  if (filename.startsWith('luz-')) return 'luz';

  return null;
};

export const GALLERY_IMAGES: GalleryImage[] = [
  {
    id: '1',
    src: '/assets/images/photos/gallery/tattoo/debi-couple-fineline-mountain-night-linework.jpg',
    optimizedSrc:
      '/assets/images/photos/gallery/optimized/debi-couple-fineline-mountain-night-linework',
    alt: 'Linienarbeit-Tattoo, Motiv 1 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 1',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: true,
  },
  {
    id: '2',
    src: '/assets/images/photos/gallery/tattoo/debi-maori-full-sleave.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-maori-full-sleave',
    alt: 'Maori-Tattoo, Motiv 2 aus dem Medusa Studio',
    title: 'Maori Motiv 2',
    category: 'Maori',
    style: 'Maori',
    width: 1170,
    height: 1445,
    objectPosition: 'center center',
    priority: true,
  },
  {
    id: '3',
    src: '/assets/images/photos/gallery/tattoo/debi-oldschool-old-rare-car.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-oldschool-old-rare-car',
    alt: 'Old School-Tattoo, Motiv 3 aus dem Medusa Studio',
    title: 'Old School Motiv 3',
    category: 'Old School',
    style: 'Old School',
    width: 1536,
    height: 1024,
    objectPosition: 'center center',
    priority: true,
  },
  {
    id: '4',
    src: '/assets/images/photos/gallery/tattoo/debi-oldschool-chain.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-oldschool-chain',
    alt: 'Old School-Tattoo, Motiv 4 aus dem Medusa Studio',
    title: 'Old School Motiv 4',
    category: 'Old School',
    style: 'Old School',
    width: 1536,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '5',
    src: '/assets/images/photos/gallery/tattoo/debi-oldschool-linework.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-oldschool-linework',
    alt: 'Old School-Tattoo, Motiv 5 aus dem Medusa Studio',
    title: 'Old School Motiv 5',
    category: 'Old School',
    style: 'Old School',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '6',
    src: '/assets/images/photos/gallery/tattoo/debi-pistol-indianer.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-pistol-indianer',
    alt: 'Realismus-Tattoo, Motiv 6 aus dem Medusa Studio',
    title: 'Realismus Motiv 6',
    category: 'Realismus',
    style: 'Realismus',
    width: 1536,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '7',
    src: '/assets/images/photos/gallery/tattoo/debi-abstract-marine-linework-concept.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-abstract-marine-linework-concept',
    alt: 'Linienarbeit-Tattoo, Motiv 7 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 7',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 896,
    height: 1184,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '8',
    src: '/assets/images/photos/gallery/tattoo/debi-asian-script-lettering-bold.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-asian-script-lettering-bold',
    alt: 'Linienarbeit-Tattoo, Motiv 8 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 8',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1570,
    height: 2048,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '9',
    src: '/assets/images/photos/gallery/tattoo/debi-blackandgrey-arabic-lettering-bold.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-blackandgrey-arabic-lettering-bold',
    alt: 'Linienarbeit-Tattoo, Motiv 9 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 9',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 665,
    height: 1182,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '10',
    src: '/assets/images/photos/gallery/tattoo/debi-blackandgrey-biomechanical-chest.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-blackandgrey-biomechanical-chest',
    alt: 'Biomechanisch-Tattoo, Motiv 10 aus dem Medusa Studio',
    title: 'Biomechanisch Motiv 10',
    category: 'Biomechanisch',
    style: 'Biomechanisch',
    width: 1376,
    height: 768,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '11',
    src: '/assets/images/photos/gallery/tattoo/debi-blackandgrey-katana-floral.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-blackandgrey-katana-floral',
    alt: 'Japanisch-Tattoo, Motiv 11 aus dem Medusa Studio',
    title: 'Japanisch Motiv 11',
    category: 'Japanisch',
    style: 'Japanisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '12',
    src: '/assets/images/photos/gallery/tattoo/debi-blackwork-anime-portrait.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-blackwork-anime-portrait',
    alt: 'Portrait-Tattoo, Motiv 12 aus dem Medusa Studio',
    title: 'Portrait Motiv 12',
    category: 'Portrait',
    style: 'Portrait',
    width: 1536,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '13',
    src: '/assets/images/photos/gallery/tattoo/debi-blackwork-geometric-bodycomposition.jpg',
    optimizedSrc:
      '/assets/images/photos/gallery/optimized/debi-blackwork-geometric-bodycomposition',
    alt: 'Geometrisch-Tattoo, Motiv 13 aus dem Medusa Studio',
    title: 'Geometrisch Motiv 13',
    category: 'Geometrisch',
    style: 'Geometrisch',
    width: 886,
    height: 886,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '14',
    src: '/assets/images/photos/gallery/tattoo/debi-blackwork-sunface-classical.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-blackwork-sunface-classical',
    alt: 'Blackwork-Tattoo, Motiv 14 aus dem Medusa Studio',
    title: 'Blackwork Motiv 14',
    category: 'Blackwork',
    style: 'Blackwork',
    width: 1024,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '15',
    src: '/assets/images/photos/gallery/tattoo/debi-bold-linework-roman-portrait.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-bold-linework-roman-portrait',
    alt: 'Linienarbeit-Tattoo, Motiv 15 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 15',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '16',
    src: '/assets/images/photos/gallery/tattoo/debi-darkart-brain-skull-illustrative.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-darkart-brain-skull-illustrative',
    alt: 'Realismus-Tattoo, Motiv 16 aus dem Medusa Studio',
    title: 'Realismus Motiv 16',
    category: 'Realismus',
    style: 'Realismus',
    width: 1376,
    height: 768,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '17',
    src: '/assets/images/photos/gallery/tattoo/debi-fineline-ornamental-botanical-blackwork.jpg',
    optimizedSrc:
      '/assets/images/photos/gallery/optimized/debi-fineline-ornamental-botanical-blackwork',
    alt: 'Linienarbeit-Tattoo, Motiv 17 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 17',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '18',
    src: '/assets/images/photos/gallery/tattoo/debi-fineline-lettering-collarbone.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-fineline-lettering-collarbone',
    alt: 'Linienarbeit-Tattoo, Motiv 18 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 18',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1086,
    height: 724,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '19',
    src: '/assets/images/photos/gallery/tattoo/debi-fineline-nature-series-circular.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-fineline-nature-series-circular',
    alt: 'Linienarbeit-Tattoo, Motiv 19 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 19',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1376,
    height: 768,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '20',
    src: '/assets/images/photos/gallery/tattoo/debi-floral-calligraphy-forearm-design.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-floral-calligraphy-forearm-design',
    alt: 'Linienarbeit-Tattoo, Motiv 20 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 20',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 724,
    height: 1086,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '21',
    src: '/assets/images/photos/gallery/tattoo/debi-illustrative-wings-centerpiece.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-illustrative-wings-centerpiece',
    alt: 'Realismus-Tattoo, Motiv 21 aus dem Medusa Studio',
    title: 'Realismus Motiv 21',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '22',
    src: '/assets/images/photos/gallery/tattoo/debi-lettering-oldenglish-minimal.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-lettering-oldenglish-minimal',
    alt: 'Linienarbeit-Tattoo, Motiv 22 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 22',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 896,
    height: 1200,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '23',
    src: '/assets/images/photos/gallery/tattoo/debi-linework-abstract-mandala-minimal.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-linework-abstract-mandala-minimal',
    alt: 'Geometrisch-Tattoo, Motiv 23 aus dem Medusa Studio',
    title: 'Geometrisch Motiv 23',
    category: 'Geometrisch',
    style: 'Geometrisch',
    width: 1376,
    height: 768,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '24',
    src: '/assets/images/photos/gallery/tattoo/debi-linework-logo-franchise.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-linework-logo-franchise',
    alt: 'Linienarbeit-Tattoo, Motiv 24 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 24',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1008,
    height: 779,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '25',
    src: '/assets/images/photos/gallery/tattoo/debi-micro-ornamental-face.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-micro-ornamental-face',
    alt: 'Linienarbeit-Tattoo, Motiv 25 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 25',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 768,
    height: 1376,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '26',
    src: '/assets/images/photos/gallery/tattoo/debi-minimal-lettering-hip.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-minimal-lettering-hip',
    alt: 'Linienarbeit-Tattoo, Motiv 26 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 26',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1264,
    height: 848,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '27',
    src: '/assets/images/photos/gallery/tattoo/debi-neo-traditional-rose-bold.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-neo-traditional-rose-bold',
    alt: 'Neo Traditional-Tattoo, Motiv 27 aus dem Medusa Studio',
    title: 'Neo Traditional Motiv 27',
    category: 'Neo Traditional',
    style: 'Neo Traditional',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '28',
    src: '/assets/images/photos/gallery/tattoo/debi-neo-traditional-tattoomachine-lettering.jpg',
    optimizedSrc:
      '/assets/images/photos/gallery/optimized/debi-neo-traditional-tattoomachine-lettering',
    alt: 'Neo Traditional-Tattoo, Motiv 28 aus dem Medusa Studio',
    title: 'Neo Traditional Motiv 28',
    category: 'Neo Traditional',
    style: 'Neo Traditional',
    width: 1536,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '29',
    src: '/assets/images/photos/gallery/tattoo/debi-oldschool-military-skull-bold.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-oldschool-military-skull-bold',
    alt: 'Old School-Tattoo, Motiv 29 aus dem Medusa Studio',
    title: 'Old School Motiv 29',
    category: 'Old School',
    style: 'Old School',
    width: 1536,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '30',
    src: '/assets/images/photos/gallery/tattoo/debi-ornamental-spine-lotus-linework.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-ornamental-spine-lotus-linework',
    alt: 'Linienarbeit-Tattoo, Motiv 30 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 30',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '31',
    src: '/assets/images/photos/gallery/tattoo/debi-sketch-style-flying-skull.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/debi-sketch-style-flying-skull',
    alt: 'Realismus-Tattoo, Motiv 31 aus dem Medusa Studio',
    title: 'Realismus Motiv 31',
    category: 'Realismus',
    style: 'Realismus',
    width: 886,
    height: 886,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '32',
    src: '/assets/images/photos/gallery/tattoo/loui-abstract-jellyfish-blackwork.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-abstract-jellyfish-blackwork',
    alt: 'Blackwork-Tattoo, Motiv 32 aus dem Medusa Studio',
    title: 'Blackwork Motiv 32',
    category: 'Blackwork',
    style: 'Blackwork',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '33',
    src: '/assets/images/photos/gallery/tattoo/loui-angel-statue-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-angel-statue-realism',
    alt: 'Realismus-Tattoo, Motiv 33 aus dem Medusa Studio',
    title: 'Realismus Motiv 33',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '34',
    src: '/assets/images/photos/gallery/tattoo/loui-blackandgrey-basketball-scene.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackandgrey-basketball-scene',
    alt: 'Realismus-Tattoo, Motiv 34 aus dem Medusa Studio',
    title: 'Realismus Motiv 34',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '35',
    src: '/assets/images/photos/gallery/tattoo/loui-blackandgrey-bird-chestpiece.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackandgrey-bird-chestpiece',
    alt: 'Realismus-Tattoo, Motiv 35 aus dem Medusa Studio',
    title: 'Realismus Motiv 35',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '36',
    src: '/assets/images/photos/gallery/tattoo/loui-blackandgrey-eagle-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackandgrey-eagle-realism',
    alt: 'Realismus-Tattoo, Motiv 36 aus dem Medusa Studio',
    title: 'Realismus Motiv 36',
    category: 'Realismus',
    style: 'Realismus',
    width: 896,
    height: 1200,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '37',
    src: '/assets/images/photos/gallery/tattoo/loui-blackandgrey-hand-rose-coloraccent.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackandgrey-hand-rose-coloraccent',
    alt: 'Realismus-Tattoo, Motiv 37 aus dem Medusa Studio',
    title: 'Realismus Motiv 37',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '38',
    src: '/assets/images/photos/gallery/tattoo/loui-blackandgrey-mermaid-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackandgrey-mermaid-realism',
    alt: 'Realismus-Tattoo, Motiv 38 aus dem Medusa Studio',
    title: 'Realismus Motiv 38',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '39',
    src: '/assets/images/photos/gallery/tattoo/loui-blackandgrey-ram-portrait.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackandgrey-ram-portrait',
    alt: 'Portrait-Tattoo, Motiv 39 aus dem Medusa Studio',
    title: 'Portrait Motiv 39',
    category: 'Portrait',
    style: 'Portrait',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '40',
    src: '/assets/images/photos/gallery/tattoo/loui-blackandgrey-realism-sleeve.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackandgrey-realism-sleeve',
    alt: 'Realismus-Tattoo, Motiv 40 aus dem Medusa Studio',
    title: 'Realismus Motiv 40',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '41',
    src: '/assets/images/photos/gallery/tattoo/loui-blackwork-demon-portrait-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackwork-demon-portrait-tattoo',
    alt: 'Portrait-Tattoo, Motiv 41 aus dem Medusa Studio',
    title: 'Portrait Motiv 41',
    category: 'Portrait',
    style: 'Portrait',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '42',
    src: '/assets/images/photos/gallery/tattoo/loui-blackwork-moth-chest.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-blackwork-moth-chest',
    alt: 'Blackwork-Tattoo, Motiv 42 aus dem Medusa Studio',
    title: 'Blackwork Motiv 42',
    category: 'Blackwork',
    style: 'Blackwork',
    width: 1024,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '43',
    src: '/assets/images/photos/gallery/tattoo/loui-cat-floral-composition.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-cat-floral-composition',
    alt: 'Realismus-Tattoo, Motiv 43 aus dem Medusa Studio',
    title: 'Realismus Motiv 43',
    category: 'Realismus',
    style: 'Realismus',
    width: 864,
    height: 1232,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '44',
    src: '/assets/images/photos/gallery/tattoo/loui-cherry-blossom-band-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-cherry-blossom-band-tattoo',
    alt: 'Realismus-Tattoo, Motiv 44 aus dem Medusa Studio',
    title: 'Realismus Motiv 44',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '45',
    src: '/assets/images/photos/gallery/tattoo/loui-colorful-fox-floral-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-colorful-fox-floral-tattoo',
    alt: 'Farbtattoo-Tattoo, Motiv 45 aus dem Medusa Studio',
    title: 'Farbtattoo Motiv 45',
    category: 'Farbtattoo',
    style: 'Farbtattoo',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '46',
    src: '/assets/images/photos/gallery/tattoo/loui-colorful-poppy-bee-shoulder.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-colorful-poppy-bee-shoulder',
    alt: 'Farbtattoo-Tattoo, Motiv 46 aus dem Medusa Studio',
    title: 'Farbtattoo Motiv 46',
    category: 'Farbtattoo',
    style: 'Farbtattoo',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '47',
    src: '/assets/images/photos/gallery/tattoo/loui-cosmic-planet-watercolor-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-cosmic-planet-watercolor-tattoo',
    alt: 'Farbtattoo-Tattoo, Motiv 47 aus dem Medusa Studio',
    title: 'Farbtattoo Motiv 47',
    category: 'Farbtattoo',
    style: 'Farbtattoo',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '48',
    src: '/assets/images/photos/gallery/tattoo/loui-dark-fantasy-fairy-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-dark-fantasy-fairy-tattoo',
    alt: 'Realismus-Tattoo, Motiv 48 aus dem Medusa Studio',
    title: 'Realismus Motiv 48',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '49',
    src: '/assets/images/photos/gallery/tattoo/loui-dragon-watercolor-backpiece.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-dragon-watercolor-backpiece',
    alt: 'Farbtattoo-Tattoo, Motiv 49 aus dem Medusa Studio',
    title: 'Farbtattoo Motiv 49',
    category: 'Farbtattoo',
    style: 'Farbtattoo',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '50',
    src: '/assets/images/photos/gallery/tattoo/loui-fineline-butterfly-ornamental.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-fineline-butterfly-ornamental',
    alt: 'Linienarbeit-Tattoo, Motiv 50 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 50',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '51',
    src: '/assets/images/photos/gallery/tattoo/loui-fineline-ornamental-key.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-fineline-ornamental-key',
    alt: 'Linienarbeit-Tattoo, Motiv 51 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 51',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '52',
    src: '/assets/images/photos/gallery/tattoo/loui-floral-branch-rib-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-floral-branch-rib-tattoo',
    alt: 'Realismus-Tattoo, Motiv 52 aus dem Medusa Studio',
    title: 'Realismus Motiv 52',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '53',
    src: '/assets/images/photos/gallery/tattoo/loui-geometric-rose-watercolor-sleeve.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-geometric-rose-watercolor-sleeve',
    alt: 'Geometrisch-Tattoo, Motiv 53 aus dem Medusa Studio',
    title: 'Geometrisch Motiv 53',
    category: 'Geometrisch',
    style: 'Geometrisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '54',
    src: '/assets/images/photos/gallery/tattoo/loui-gothic-lettering-statement.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-gothic-lettering-statement',
    alt: 'Linienarbeit-Tattoo, Motiv 54 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 54',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '55',
    src: '/assets/images/photos/gallery/tattoo/loui-micro-dragon-blackandgrey.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-micro-dragon-blackandgrey',
    alt: 'Realismus-Tattoo, Motiv 55 aus dem Medusa Studio',
    title: 'Realismus Motiv 55',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '56',
    src: '/assets/images/photos/gallery/tattoo/loui-micro-realistic-dog-portrait.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-micro-realistic-dog-portrait',
    alt: 'Portrait-Tattoo, Motiv 56 aus dem Medusa Studio',
    title: 'Portrait Motiv 56',
    category: 'Portrait',
    style: 'Portrait',
    width: 1024,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '57',
    src: '/assets/images/photos/gallery/tattoo/loui-ornamental-compass-floral.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-ornamental-compass-floral',
    alt: 'Linienarbeit-Tattoo, Motiv 57 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 57',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '58',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-angel-wings-back.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-angel-wings-back',
    alt: 'Realismus-Tattoo, Motiv 58 aus dem Medusa Studio',
    title: 'Realismus Motiv 58',
    category: 'Realismus',
    style: 'Realismus',
    width: 1536,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '59',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-bird-duo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-bird-duo',
    alt: 'Realismus-Tattoo, Motiv 59 aus dem Medusa Studio',
    title: 'Realismus Motiv 59',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '60',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-butterfly-colorwork.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-butterfly-colorwork',
    alt: 'Realismus-Tattoo, Motiv 60 aus dem Medusa Studio',
    title: 'Realismus Motiv 60',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '61',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-eagle-chest.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-eagle-chest',
    alt: 'Realismus-Tattoo, Motiv 61 aus dem Medusa Studio',
    title: 'Realismus Motiv 61',
    category: 'Realismus',
    style: 'Realismus',
    width: 864,
    height: 1232,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '62',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-eye-color-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-eye-color-tattoo',
    alt: 'Realismus-Tattoo, Motiv 62 aus dem Medusa Studio',
    title: 'Realismus Motiv 62',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '63',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-hands-sketch.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-hands-sketch',
    alt: 'Realismus-Tattoo, Motiv 63 aus dem Medusa Studio',
    title: 'Realismus Motiv 63',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '64',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-jellyfish-underwater-1.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-jellyfish-underwater-1',
    alt: 'Realismus-Tattoo, Motiv 64 aus dem Medusa Studio',
    title: 'Realismus Motiv 64',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '65',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-jellyfish-underwater.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-jellyfish-underwater',
    alt: 'Realismus-Tattoo, Motiv 65 aus dem Medusa Studio',
    title: 'Realismus Motiv 65',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '66',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-praying-hands-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-praying-hands-tattoo',
    alt: 'Realismus-Tattoo, Motiv 66 aus dem Medusa Studio',
    title: 'Realismus Motiv 66',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '67',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-pretzel-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-pretzel-tattoo',
    alt: 'Realismus-Tattoo, Motiv 67 aus dem Medusa Studio',
    title: 'Realismus Motiv 67',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '68',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-red-rose-shoulder.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-red-rose-shoulder',
    alt: 'Realismus-Tattoo, Motiv 68 aus dem Medusa Studio',
    title: 'Realismus Motiv 68',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '69',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-sleeping-cat.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-sleeping-cat',
    alt: 'Realismus-Tattoo, Motiv 69 aus dem Medusa Studio',
    title: 'Realismus Motiv 69',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '70',
    src: '/assets/images/photos/gallery/tattoo/loui-realistic-tiger-portrait-forearm.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-realistic-tiger-portrait-forearm',
    alt: 'Portrait-Tattoo, Motiv 70 aus dem Medusa Studio',
    title: 'Portrait Motiv 70',
    category: 'Portrait',
    style: 'Portrait',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '71',
    src: '/assets/images/photos/gallery/tattoo/loui-renaissance-angel-moon-scene.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-renaissance-angel-moon-scene',
    alt: 'Realismus-Tattoo, Motiv 71 aus dem Medusa Studio',
    title: 'Realismus Motiv 71',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '72',
    src: '/assets/images/photos/gallery/tattoo/loui-tiger-peony-blackgrey.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-tiger-peony-blackgrey',
    alt: 'Realismus-Tattoo, Motiv 72 aus dem Medusa Studio',
    title: 'Realismus Motiv 72',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '73',
    src: '/assets/images/photos/gallery/tattoo/loui-triangle-ship-linework.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/loui-triangle-ship-linework',
    alt: 'Linienarbeit-Tattoo, Motiv 73 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 73',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '74',
    src: '/assets/images/photos/gallery/tattoo/luz-fineline-lettering.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fineline-lettering',
    alt: 'Linienarbeit-Tattoo, Motiv 74 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 74',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '75',
    src: '/assets/images/photos/gallery/tattoo/luz-oneline-face.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-oneline-face',
    alt: 'Linienarbeit-Tattoo, Motiv 75 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 75',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '76',
    src: '/assets/images/photos/gallery/tattoo/luz-anatomical-heart-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-anatomical-heart-realism',
    alt: 'Realismus-Tattoo, Motiv 76 aus dem Medusa Studio',
    title: 'Realismus Motiv 76',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '77',
    src: '/assets/images/photos/gallery/tattoo/luz-angel-warrior-blackgrey.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-angel-warrior-blackgrey',
    alt: 'Realismus-Tattoo, Motiv 77 aus dem Medusa Studio',
    title: 'Realismus Motiv 77',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '78',
    src: '/assets/images/photos/gallery/tattoo/luz-blackgrey-stingray.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-blackgrey-stingray',
    alt: 'Realismus-Tattoo, Motiv 78 aus dem Medusa Studio',
    title: 'Realismus Motiv 78',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '79',
    src: '/assets/images/photos/gallery/tattoo/luz-blackwork-skull-handprint.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-blackwork-skull-handprint',
    alt: 'Blackwork-Tattoo, Motiv 79 aus dem Medusa Studio',
    title: 'Blackwork Motiv 79',
    category: 'Blackwork',
    style: 'Blackwork',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '80',
    src: '/assets/images/photos/gallery/tattoo/luz-blindfolded-angel-woman.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-blindfolded-angel-woman',
    alt: 'Realismus-Tattoo, Motiv 80 aus dem Medusa Studio',
    title: 'Realismus Motiv 80',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '81',
    src: '/assets/images/photos/gallery/tattoo/luz-botanical-fineline-branch.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-botanical-fineline-branch',
    alt: 'Linienarbeit-Tattoo, Motiv 81 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 81',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '82',
    src: '/assets/images/photos/gallery/tattoo/luz-botanical-rat-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-botanical-rat-tattoo',
    alt: 'Linienarbeit-Tattoo, Motiv 82 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 82',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '83',
    src: '/assets/images/photos/gallery/tattoo/luz-brian-griffin-cartoon.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-brian-griffin-cartoon',
    alt: 'Realismus-Tattoo, Motiv 83 aus dem Medusa Studio',
    title: 'Realismus Motiv 83',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '84',
    src: '/assets/images/photos/gallery/tattoo/luz-cartoon-jester-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-cartoon-jester-tattoo',
    alt: 'Realismus-Tattoo, Motiv 84 aus dem Medusa Studio',
    title: 'Realismus Motiv 84',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '85',
    src: '/assets/images/photos/gallery/tattoo/luz-chaotic-line-art-face.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-chaotic-line-art-face',
    alt: 'Realismus-Tattoo, Motiv 85 aus dem Medusa Studio',
    title: 'Realismus Motiv 85',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '86',
    src: '/assets/images/photos/gallery/tattoo/luz-curled-bull-minimal.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-curled-bull-minimal',
    alt: 'Minimalistisch-Tattoo, Motiv 86 aus dem Medusa Studio',
    title: 'Minimalistisch Motiv 86',
    category: 'Minimalistisch',
    style: 'Minimalistisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '87',
    src: '/assets/images/photos/gallery/tattoo/luz-disco-ball-linework.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-disco-ball-linework',
    alt: 'Linienarbeit-Tattoo, Motiv 87 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 87',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '88',
    src: '/assets/images/photos/gallery/tattoo/luz-edelweiss-flower-fineline.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-edelweiss-flower-fineline',
    alt: 'Linienarbeit-Tattoo, Motiv 88 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 88',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '89',
    src: '/assets/images/photos/gallery/tattoo/luz-fine-line-flower-bouquet.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fine-line-flower-bouquet',
    alt: 'Realismus-Tattoo, Motiv 89 aus dem Medusa Studio',
    title: 'Realismus Motiv 89',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '90',
    src: '/assets/images/photos/gallery/tattoo/luz-fine-line-lettering-spanish.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fine-line-lettering-spanish',
    alt: 'Linienarbeit-Tattoo, Motiv 90 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 90',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '91',
    src: '/assets/images/photos/gallery/tattoo/luz-fine-script-quote-lettering.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fine-script-quote-lettering',
    alt: 'Linienarbeit-Tattoo, Motiv 91 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 91',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '92',
    src: '/assets/images/photos/gallery/tattoo/luz-fine-script-single-word.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fine-script-single-word',
    alt: 'Linienarbeit-Tattoo, Motiv 92 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 92',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '93',
    src: '/assets/images/photos/gallery/tattoo/luz-fineline-botanical-flower.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fineline-botanical-flower',
    alt: 'Linienarbeit-Tattoo, Motiv 93 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 93',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '94',
    src: '/assets/images/photos/gallery/tattoo/luz-fineline-fairy-silhouette.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fineline-fairy-silhouette',
    alt: 'Linienarbeit-Tattoo, Motiv 94 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 94',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '95',
    src: '/assets/images/photos/gallery/tattoo/luz-fineline-flying-dragon.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fineline-flying-dragon',
    alt: 'Linienarbeit-Tattoo, Motiv 95 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 95',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '96',
    src: '/assets/images/photos/gallery/tattoo/luz-fineline-vintage-film-camera.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-fineline-vintage-film-camera',
    alt: 'Linienarbeit-Tattoo, Motiv 96 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 96',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '97',
    src: '/assets/images/photos/gallery/tattoo/luz-flying-swallow-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-flying-swallow-realism',
    alt: 'Realismus-Tattoo, Motiv 97 aus dem Medusa Studio',
    title: 'Realismus Motiv 97',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '98',
    src: '/assets/images/photos/gallery/tattoo/luz-geometric-tree-of-life.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-geometric-tree-of-life',
    alt: 'Geometrisch-Tattoo, Motiv 98 aus dem Medusa Studio',
    title: 'Geometrisch Motiv 98',
    category: 'Geometrisch',
    style: 'Geometrisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '99',
    src: '/assets/images/photos/gallery/tattoo/luz-heart-banner-name-traditional.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-heart-banner-name-traditional',
    alt: 'Old School-Tattoo, Motiv 99 aus dem Medusa Studio',
    title: 'Old School Motiv 99',
    category: 'Old School',
    style: 'Old School',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '100',
    src: '/assets/images/photos/gallery/tattoo/luz-japanese-hannya-mask.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-japanese-hannya-mask',
    alt: 'Japanisch-Tattoo, Motiv 100 aus dem Medusa Studio',
    title: 'Japanisch Motiv 100',
    category: 'Japanisch',
    style: 'Japanisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '101',
    src: '/assets/images/photos/gallery/tattoo/luz-king-queen-chess-piece.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-king-queen-chess-piece',
    alt: 'Realismus-Tattoo, Motiv 101 aus dem Medusa Studio',
    title: 'Realismus Motiv 101',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '102',
    src: '/assets/images/photos/gallery/tattoo/luz-mandala-ear-ornamental.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-mandala-ear-ornamental',
    alt: 'Geometrisch-Tattoo, Motiv 102 aus dem Medusa Studio',
    title: 'Geometrisch Motiv 102',
    category: 'Geometrisch',
    style: 'Geometrisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '103',
    src: '/assets/images/photos/gallery/tattoo/luz-medusa-style-bust.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-medusa-style-bust',
    alt: 'Realismus-Tattoo, Motiv 103 aus dem Medusa Studio',
    title: 'Realismus Motiv 103',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '104',
    src: '/assets/images/photos/gallery/tattoo/luz-mini-cherry-color.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-mini-cherry-color',
    alt: 'Farbtattoo-Tattoo, Motiv 104 aus dem Medusa Studio',
    title: 'Farbtattoo Motiv 104',
    category: 'Farbtattoo',
    style: 'Farbtattoo',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '105',
    src: '/assets/images/photos/gallery/tattoo/luz-minimal-branch-moon.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-minimal-branch-moon',
    alt: 'Minimalistisch-Tattoo, Motiv 105 aus dem Medusa Studio',
    title: 'Minimalistisch Motiv 105',
    category: 'Minimalistisch',
    style: 'Minimalistisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '106',
    src: '/assets/images/photos/gallery/tattoo/luz-minimal-daisy-linework.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-minimal-daisy-linework',
    alt: 'Linienarbeit-Tattoo, Motiv 106 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 106',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '107',
    src: '/assets/images/photos/gallery/tattoo/luz-minimal-star-cluster.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-minimal-star-cluster',
    alt: 'Minimalistisch-Tattoo, Motiv 107 aus dem Medusa Studio',
    title: 'Minimalistisch Motiv 107',
    category: 'Minimalistisch',
    style: 'Minimalistisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '108',
    src: '/assets/images/photos/gallery/tattoo/luz-neo-tribal-cross.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-neo-tribal-cross',
    alt: 'Maori-Tattoo, Motiv 108 aus dem Medusa Studio',
    title: 'Maori Motiv 108',
    category: 'Maori',
    style: 'Maori',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '109',
    src: '/assets/images/photos/gallery/tattoo/luz-ok-hand-symbol-linework.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-ok-hand-symbol-linework',
    alt: 'Linienarbeit-Tattoo, Motiv 109 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 109',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '110',
    src: '/assets/images/photos/gallery/tattoo/luz-old-english-lettering-name-year.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-old-english-lettering-name-year',
    alt: 'Linienarbeit-Tattoo, Motiv 110 aus dem Medusa Studio',
    title: 'Linienarbeit Motiv 110',
    category: 'Linienarbeit',
    style: 'Linienarbeit',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '111',
    src: '/assets/images/photos/gallery/tattoo/luz-raven-realism-blackgrey.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-raven-realism-blackgrey',
    alt: 'Realismus-Tattoo, Motiv 111 aus dem Medusa Studio',
    title: 'Realismus Motiv 111',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '112',
    src: '/assets/images/photos/gallery/tattoo/luz-raven-skull-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-raven-skull-realism',
    alt: 'Realismus-Tattoo, Motiv 112 aus dem Medusa Studio',
    title: 'Realismus Motiv 112',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '113',
    src: '/assets/images/photos/gallery/tattoo/luz-realistic-bee-lavender.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-realistic-bee-lavender',
    alt: 'Realismus-Tattoo, Motiv 113 aus dem Medusa Studio',
    title: 'Realismus Motiv 113',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '114',
    src: '/assets/images/photos/gallery/tattoo/luz-realistic-eye-hand.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-realistic-eye-hand',
    alt: 'Realismus-Tattoo, Motiv 114 aus dem Medusa Studio',
    title: 'Realismus Motiv 114',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1024,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '115',
    src: '/assets/images/photos/gallery/tattoo/luz-realistic-flying-snail.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-realistic-flying-snail',
    alt: 'Realismus-Tattoo, Motiv 115 aus dem Medusa Studio',
    title: 'Realismus Motiv 115',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '116',
    src: '/assets/images/photos/gallery/tattoo/luz-realistic-gecko-lizard.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-realistic-gecko-lizard',
    alt: 'Realismus-Tattoo, Motiv 116 aus dem Medusa Studio',
    title: 'Realismus Motiv 116',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '117',
    src: '/assets/images/photos/gallery/tattoo/luz-realistic-lotus-blackgrey.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-realistic-lotus-blackgrey',
    alt: 'Realismus-Tattoo, Motiv 117 aus dem Medusa Studio',
    title: 'Realismus Motiv 117',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '118',
    src: '/assets/images/photos/gallery/tattoo/luz-red-top-hat-portrait.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-red-top-hat-portrait',
    alt: 'Portrait-Tattoo, Motiv 118 aus dem Medusa Studio',
    title: 'Portrait Motiv 118',
    category: 'Portrait',
    style: 'Portrait',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '119',
    src: '/assets/images/photos/gallery/tattoo/luz-running-hurdles-scene.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-running-hurdles-scene',
    alt: 'Realismus-Tattoo, Motiv 119 aus dem Medusa Studio',
    title: 'Realismus Motiv 119',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '120',
    src: '/assets/images/photos/gallery/tattoo/luz-samurai-swordsman-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-samurai-swordsman-realism',
    alt: 'Japanisch-Tattoo, Motiv 120 aus dem Medusa Studio',
    title: 'Japanisch Motiv 120',
    category: 'Japanisch',
    style: 'Japanisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '121',
    src: '/assets/images/photos/gallery/tattoo/luz-surreal-eye-fish.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-surreal-eye-fish',
    alt: 'Realismus-Tattoo, Motiv 121 aus dem Medusa Studio',
    title: 'Realismus Motiv 121',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '122',
    src: '/assets/images/photos/gallery/tattoo/luz-surreal-eye-headed-figure.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-surreal-eye-headed-figure',
    alt: 'Realismus-Tattoo, Motiv 122 aus dem Medusa Studio',
    title: 'Realismus Motiv 122',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '123',
    src: '/assets/images/photos/gallery/tattoo/luz-tattoo-artist-work-studio.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-tattoo-artist-work-studio',
    alt: 'Realismus-Tattoo, Motiv 123 aus dem Medusa Studio',
    title: 'Realismus Motiv 123',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '124',
    src: '/assets/images/photos/gallery/tattoo/luz-tattoo-artist-work-studio2.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-tattoo-artist-work-studio2',
    alt: 'Realismus-Tattoo, Motiv 124 aus dem Medusa Studio',
    title: 'Realismus Motiv 124',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '125',
    src: '/assets/images/photos/gallery/tattoo/luz-tattoo-artist-working.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-tattoo-artist-working',
    alt: 'Realismus-Tattoo, Motiv 125 aus dem Medusa Studio',
    title: 'Realismus Motiv 125',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '126',
    src: '/assets/images/photos/gallery/tattoo/luz-tiny-star-tattoo.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-tiny-star-tattoo',
    alt: 'Minimalistisch-Tattoo, Motiv 126 aus dem Medusa Studio',
    title: 'Minimalistisch Motiv 126',
    category: 'Minimalistisch',
    style: 'Minimalistisch',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '127',
    src: '/assets/images/photos/gallery/tattoo/luz-traditional-heart-banner.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-traditional-heart-banner',
    alt: 'Old School-Tattoo, Motiv 127 aus dem Medusa Studio',
    title: 'Old School Motiv 127',
    category: 'Old School',
    style: 'Old School',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '128',
    src: '/assets/images/photos/gallery/tattoo/luz-tree-hand-roots.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-tree-hand-roots',
    alt: 'Realismus-Tattoo, Motiv 128 aus dem Medusa Studio',
    title: 'Realismus Motiv 128',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '129',
    src: '/assets/images/photos/gallery/tattoo/luz-viking-warrior-woman-realism.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-viking-warrior-woman-realism',
    alt: 'Realismus-Tattoo, Motiv 129 aus dem Medusa Studio',
    title: 'Realismus Motiv 129',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
  {
    id: '130',
    src: '/assets/images/photos/gallery/tattoo/luz-winged-sword-eye.jpg',
    optimizedSrc: '/assets/images/photos/gallery/optimized/luz-winged-sword-eye',
    alt: 'Realismus-Tattoo, Motiv 130 aus dem Medusa Studio',
    title: 'Realismus Motiv 130',
    category: 'Realismus',
    style: 'Realismus',
    width: 1024,
    height: 1536,
    objectPosition: 'center center',
    priority: false,
  },
];

const PREPARED_GALLERY_IMAGES: GalleryFilterImage[] = GALLERY_IMAGES.flatMap((image) => {
  if (DUPLICATE_GALLERY_IMAGE_IDS.has(image.id)) {
    return [];
  }

  const artistId = getArtistIdFromImage(image);
  if (!artistId) {
    return [];
  }

  return [
    {
      ...image,
      artistId,
      artistName: GALLERY_ARTISTS[artistId].label,
      styleKey: getStyleKey(image.style),
    },
  ];
});

export const getHeroImages = (): GalleryFilterImage[] => {
  return PREPARED_GALLERY_IMAGES.filter((img) => img.priority === true);
};

export const getGalleryPreviewImages = (limit = 8): GalleryFilterImage[] => {
  return PREPARED_GALLERY_IMAGES.slice(0, limit);
};

export const getImageById = (id: string): GalleryFilterImage | undefined => {
  return PREPARED_GALLERY_IMAGES.find((img) => img.id === id);
};

export const getLocalizedGalleryImages = (language: GalleryLocale): GalleryFilterImage[] => {
  return PREPARED_GALLERY_IMAGES.map((image) => ({
    ...image,
    ...getLocalizedImageCopy(image, language),
  }));
};

export const getGalleryArtistOptions = (): GalleryArtistOption[] => {
  const visibleArtistIds = new Set(PREPARED_GALLERY_IMAGES.map((image) => image.artistId));
  return Object.values(GALLERY_ARTISTS).filter((artist) => visibleArtistIds.has(artist.id));
};

/**
 * Generate srcset for responsive images
 * @param optimizedSrc Base path without size suffix
 * @param format 'avif' or 'webp'
 * @param sizes Array of widths (e.g., [400, 640, 960])
 */
export const generateSrcSet = (
  optimizedSrc: string,
  format: 'avif' | 'webp',
  sizes: number[] = [400, 640, 960],
): string => {
  const encodedBase = encodeURI(optimizedSrc);
  return sizes.map((size) => `${encodedBase}-${size}w.${format} ${size}w`).join(', ');
};

/**
 * Generate picture element sources for a gallery image
 */
export const getImageSources = (
  image: GalleryImage,
  sizes: string = '(max-width: 767px) 100vw, 50vw',
) => {
  return {
    avifSrcSet: generateSrcSet(image.optimizedSrc, 'avif'),
    webpSrcSet: generateSrcSet(image.optimizedSrc, 'webp'),
    fallbackSrc: image.src,
    sizes,
    alt: image.alt,
    width: image.width,
    height: image.height,
    loading: image.priority ? 'eager' : ('lazy' as const),
  };
};

export default GALLERY_IMAGES;
